# Generated by Django 3.2.7 on 2021-09-26 10:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chandao_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_name', models.CharField(default='', max_length=100)),
                ('vul_name', models.CharField(max_length=200)),
                ('md5', models.CharField(max_length=100)),
                ('Abstract', models.TextField()),
                ('FileName', models.CharField(max_length=50)),
                ('FilePath', models.CharField(max_length=200)),
                ('LineStart', models.CharField(max_length=10)),
                ('describe', models.TextField()),
                ('Recommendation', models.TextField()),
                ('hidden', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
            options={
                'permissions': (('chandao_index', '展示禅道主页'), ('hidden_vul', '隐藏发送到禅道的漏洞'), ('filter_vul', '过滤发送到禅道的漏洞'), ('send_vul', '发送到禅道的漏洞')),
            },
        ),
        migrations.CreateModel(
            name='chandao_person_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=10)),
                ('ename', models.CharField(max_length=100)),
                ('cname', models.CharField(max_length=200)),
                ('pid', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='proj_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('git', models.CharField(blank=True, max_length=100, null=True)),
                ('total', models.CharField(default='0', max_length=10, null=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default=1)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('svn', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'permissions': (('upload_code_and_scan', '可以上传代码并且进行代码审计扫描'), ('restart_scan', '重新进行代码审计扫描'), ('display_projects', '展示所有代码审计项目'), ('display_info', '展示一个项目的详细信息'), ('delelte_project', '删除代码审计项目')),
            },
        ),
        migrations.CreateModel(
            name='vul_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('risk', models.CharField(max_length=10)),
                ('Abstract', models.TextField()),
                ('FileName', models.CharField(max_length=50)),
                ('vtoken', models.CharField(max_length=50)),
                ('FilePath', models.CharField(max_length=200)),
                ('LineStart', models.CharField(max_length=10)),
                ('Snippet', models.TextField()),
                ('full_code', models.TextField()),
                ('extend', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now=True)),
                ('proj_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CodeAudit.proj_info')),
            ],
            options={
                'permissions': (('vullist', '返回一个项目的漏洞列表'), ('vuldetail', '返回一个项目的漏洞列表具体信息')),
            },
        ),
    ]
